### ISSUE TITLE
After flashing the recovery, phone reboots showing this error.

### ISSUE THREAD

**Issue by o0Mardev** [o0Mardev/TWRP_CPH2021#2]
As mentioned in the title once the recovery is flashed I proceed to restart the device in recovery, then after a few seconds there is this error on the screen:

`Serial is not match fastboot_unlock_verify fail`

This is the part of the ramoops which shows this message:
`
[    6.612186]  (0)[1:init]is_fastboot_adb_enabled: device_lock_state_new=unlocked, device_lock_state_old=0
[    6.612212]  (0)[1:init]is_fastboot_adb_enabled: config_special=0,is_debuggable=0, is_cta_version=0,is_allcommode=0,is_oppo_secure=0
[    6.612224]  (0)[1:init]adb_enable_verify: Error platform mtk: mt6771
[    6.612439]  (0)[1:init]Roland serialno is Y9UO7PMBWW4STG5P
[    6.614945]  (0)[1:init]adb_enable_verify_mtk: the serial is not match
[    6.614972]  (0)[1:init]adb_enable_verify: status  : 0
`

And here it is the full log attached.
[console-ramoops-0.txt](https://github.com/o0Mardev/TWRP_CPH2021/files/10459346/console-ramoops-0.txt)

**Comment by Nomz420** [comment]
Oppo won't let you reboot to recovery by holding buttons if you unlocked it through mtkclient or similar. Instead reboot to recovery from Android.

**Comment by o0Mardev** [comment]
I knew this in fact after flashing the recovery using mtkclient I turned the phone back on normally, and then from the computer using adb I used the command "adb reboot recovery".

**Comment by Nomz420** [comment]
Can you send me the recovery.img so I can try it?
Also check if you get different results when rebooting to recovery with an app requiring root like Simple Reboot.

**Comment by o0Mardev** [comment]
Okay, I'll post the recovery image on release because the file it's too big, I'll definitely try that.

**Comment by Nomz420** [comment]
Tried the recovery. Looks like this TWRP fails to boot, then reboots to the `Serial is not match` error, then reboots to recovery again which fails to boot, and we go a full circle.
This TWRP just doesn't work and you can't do anything about the `Serial is not match` error (unless you patch the preloader somehow to disable LK verification, then you can disable this error but it won't change anything yet). Instead try to make this device tree work for this device. Just copy pasting another TWRP with the similar SoC won't work.

**Comment by o0Mardev** [comment]
I see, thank you very much for the help anyway.

**Comment by muhammadrafiasyddiq** [comment]
> I see, thank you very much for the help anyway.

i use this can booting

this device use avb sign 
you try sign twrp use avb

**Comment by o0Mardev** [comment]
I'm sorry but I think I don't understand, what do you mean by "i use this can booting"?
And how should I sign the twrp? I've never done it and looking on the internet I can't find much.

**Comment by muhammadrafiasyddiq** [comment]
> I'm sorry but I think I don't understand, what do you mean by "i use this can booting"? And how should I sign the twrp? I've never done it and looking on the internet I can't find much.

try to patch magisk recovery.img stock if you see the boot image has been signed which avb 1.0 then your custom recovery must be signed using avbtool

**Comment by muhammadrafiasyddiq** [comment]
> I'm sorry but I think I don't understand, what do you mean by "i use this can booting"? And how should I sign the twrp? I've never done it and looking on the internet I can't find much.

![Screenshot_20230201_181652](https://user-images.githubusercontent.com/66067362/216404064-95c8dd01-13e6-407c-b196-7ba46f25040e.jpg)

**Comment by o0Mardev** [comment]
I just tried with the stock recovery here is what is written. Does not appear to be signed.
![Screenshot_2023-02-02-19-00-55-03_785cfb1f0fb0c9a2030c9b38a1c3479a](https://user-images.githubusercontent.com/83718256/216406297-e13f4c9e-2616-402f-96bf-f22ecce9e6e8.jpg)

**Comment by muhammadrafiasyddiq** [comment]
> I just tried with the stock recovery here is what is written. Does not appear to be signed. ![Screenshot_2023-02-02-19-00-55-03_785cfb1f0fb0c9a2030c9b38a1c3479a](https://user-images.githubusercontent.com/83718256/216406297-e13f4c9e-2616-402f-96bf-f22ecce9e6e8.jpg)

use fastboot oem reboot-recovery 
oppo if ubl use mtk client cannot enter twrp use button

**Comment by muhammadrafiasyddiq** [comment]
> I just tried with the stock recovery here is what is written. Does not appear to be signed. ![Screenshot_2023-02-02-19-00-55-03_785cfb1f0fb0c9a2030c9b38a1c3479a](https://user-images.githubusercontent.com/83718256/216406297-e13f4c9e-2616-402f-96bf-f22ecce9e6e8.jpg)

send you lk.img i will patch for unlock fastboot

**Comment by Nomz420** [comment]
> send you lk.img i will patch for unlock fastboot

Patching LK won't work. 
https://github.com/R0rt1z2/oplus-unlock/issues/3

**Comment by muhammadrafiasyddiq** [comment]
> > send you lk.img i will patch for unlock fastboot
> 
> Patching LK won't work. [R0rt1z2/oplus-unlock#3](https://github.com/R0rt1z2/oplus-unlock/issues/3)

yes for Android 11 
but android 9 work

**Comment by muhammadrafiasyddiq** [comment]
> > send you lk.img i will patch for unlock fastboot
> 
> Patching LK won't work. [R0rt1z2/oplus-unlock#3](https://github.com/R0rt1z2/oplus-unlock/issues/3)

me oppo f11  mt6771 now android 10 
have twrp port from realme u1
fastboot unlocked
custom kernel from source oppo a91 
use config oppo_18531 
worked

**Comment by o0Mardev** [comment]
I'm not at home right now, as soon as I can I'll share the lk image.
And I'll give it a try.

**Comment by o0Mardev** [comment]
The funny thing is that through a porting program from Hovatek I got a working twrp recovery image but I don't have the device tree, I'll post that also if it's useful.

**Comment by muhammadrafiasyddiq** [comment]
> Lucunya, melalui program porting dari Hovatek saya mendapatkan gambar pemulihan twrp yang berfungsi tetapi saya tidak memiliki pohon perangkat, saya akan mempostingnya juga jika berguna.

porting hovatek? do booting?

**Comment by o0Mardev** [comment]
It was this program I think [Hovatek porting twrp](https://www.hovatek.com/forum/thread-21839.html). Yes It boots and the thinks that doesn't work are: mounting some partitions, vibration and decryption.

**Comment by muhammadrafiasyddiq** [comment]
> Program inilah yang saya pikir [Hovatek porting twrp](https://www.hovatek.com/forum/thread-21839.html) . Ya Itu boot dan pemikiran yang tidak berfungsi adalah: memasang beberapa partisi, getaran dan dekripsi.

what twrp? orangefox?

**Comment by o0Mardev** [comment]
Sorry I couldn't answer before anyway yes it's twrp. This is the lk image  (just extract the zip)
[lk-stock.img.zip](https://github.com/o0Mardev/TWRP_CPH2021/files/10578986/lk-stock.img.zip) and this Is the twrp that works but which I don't have the source  [link to Google Drive because higher than 25 MB](https://drive.google.com/file/d/1YqSJpN3cK75c0kCb2xKPecFDNyfwX5Um/view?usp=drivesdk)

**Comment by muhammadrafiasyddiq** [comment]
> Maaf saya tidak bisa menjawab sebelumnya ya itu twrp. Ini adalah gambar lk (cukup ekstrak zipnya) [lk-stock.img.zip](https://github.com/o0Mardev/TWRP_CPH2021/files/10578986/lk-stock.img.zip) dan ini adalah twrp yang berfungsi tetapi saya tidak memiliki [tautan sumber ke Google Drive karena lebih tinggi dari 25 MB](https://drive.google.com/file/d/1YqSJpN3cK75c0kCb2xKPecFDNyfwX5Um/view?usp=drivesdk)

sorry for low respon if want fast chat telegram @exalibur1

**Comment by muhammadrafiasyddiq** [comment]
> Maaf saya tidak bisa menjawab sebelumnya ya itu twrp. Ini adalah gambar lk (cukup ekstrak zipnya) [lk-stock.img.zip](https://github.com/o0Mardev/TWRP_CPH2021/files/10578986/lk-stock.img.zip) dan ini adalah twrp yang berfungsi tetapi saya tidak memiliki [tautan sumber ke Google Drive karena lebih tinggi dari 25 MB](https://drive.google.com/file/d/1YqSJpN3cK75c0kCb2xKPecFDNyfwX5Um/view?usp=drivesdk)

> 

>  `

> Maaf saya tidak bisa menjawab sebelumnya ya itu twrp. Ini adalah gambar lk (cukup ekstrak zipnya) [lk-stock.img.zip](https://github.com/o0Mardev/TWRP_CPH2021/files/10578986/lk-stock.img.zip) dan ini adalah twrp yang berfungsi tetapi saya tidak memiliki [tautan sumber ke Google Drive karena lebih tinggi dari 25 MB](https://drive.google.com/file/d/1YqSJpN3cK75c0kCb2xKPecFDNyfwX5Um/view?usp=drivesdk)

https://drive.google.com/file/d/17n-CAHiDKs-CRro8Nr3x7b6a8PxZcKl4/view?usp=drivesdk

write lk and lk2 please try under a11

**Comment by o0Mardev** [comment]
I just tried twice simply the phone refuses to boot (black screen).

**Comment by muhammadrafiasyddiq** [comment]
> Saya baru saja mencoba dua kali telepon menolak untuk boot (layar hitam).

whats you version android

**Comment by muhammadrafiasyddiq** [comment]
> I just tried twice simply the phone refuses to boot (black screen).

if android 11 i said not worked for os 11

**Comment by muhammadrafiasyddiq** [comment]
> I just tried twice simply the phone refuses to boot (black screen).

i tested other device in android 9

**Comment by o0Mardev** [comment]
yes you are right I had not read the message. I am on android 11 that's why it doesn't work.

**Comment by muhammadrafiasyddiq** [comment]
> yes you are right I had not read the message. I am on android 11 that's why it doesn't work.

chat telegram me bro github no notifications i very slow reply

**Comment by o0Mardev** [comment]
Yeah, from now I'll write you on telegram.

**Comment by Nomz420** [comment]
Can you publish the TWRP build? I want to try it out.

**Comment by o0Mardev** [comment]
> Can you publish the TWRP build? I want to try it out.

Sure, I put the build as a pre-release.

**Comment by NCLnclNCL** [comment]
> > > send you lk.img i will patch for unlock fastboot
> > 
> > 
> > Patching LK won't work. [R0rt1z2/oplus-unlock#3](https://github.com/R0rt1z2/oplus-unlock/issues/3)
> 
> me oppo f11 mt6771 now android 10 have twrp port from realme u1 fastboot unlocked custom kernel from source oppo a91 use config oppo_18531 worked

Kernel working ?
