### ISSUE TITLE
Authentication and mtkclient Connection Issues After Flashing Your Custom Recovery

### ISSUE THREAD

**Issue by Jgckm** [o0Mardev/TWRP_CPH2021#5]
I flashed your build of recovery, but my phone is unable to bypass authentication and cannot connect to the mtkclient tool. To make matters worse, I uninstalled Magisk today, so now my phone is in an unrooted state. I suspect that when I used your built recovery, it made certain modifications to the data in some partitions during boot-up, causing me to fail authentication after flashing back to the official recovery. I used the Bypass utility tool to extract a new set of payloads. The phone can function normally; it's just that connecting it to mtkclient looks like this (Apologies for my poor English).
![image](https://github.com/o0Mardev/android_device_oppo_OP4B9B/assets/51497452/e68ba7d3-3d35-45ba-a091-fcd9ec26b9de)

![image](https://github.com/o0Mardev/android_device_oppo_OP4B9B/assets/51497452/3e3015e2-386f-4f0e-bda9-0ad625fa8f35)

Preloader - Status: Waiting for PreLoader VCOM, please connect mobile
Port - Device detected :)
Preloader -     CPU:                    MT6771/MT8385/MT8183/MT8666(Helio P60/P70/G80)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x788
Preloader - Target config:              0x0
Preloader -     SBC enabled:            False
Preloader -     SLA enabled:            False
Preloader -     DAA enabled:            False
Preloader -     SWJTAG enabled:         False
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          False
Preloader -     Mem write auth:         False
Preloader -     Cmd 0xC8 blocked:       False
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      E826FA490F24B26B72B1377155E00B92
Preloader - SOC_ID:                     2203B95706CA92C63151D5A745244722BFB3BA0E0DFB490BC6AE1541875BF3F8
Port - Device detected :)
Successfully extracted preloader for this device to: preloader_oppo6771.bin
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2136.bin
xflashext - Patching da1 ...
xflashext
xflashext - [LIB]: Error on patching da1 version check...
xflashext - Patching da2 ...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       KM8V8001JM-B81
DAXFlash - UFS MID:      0xce
DAXFlash - UFS CID:      ce014b4d3856383030314a4d2d423831
DAXFlash - UFS FWVer:    31303030
DAXFlash - UFS Serial:   336261616466313432633064
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DRAM config needed for : ce014b4d3856383030314a4d2d423831
DAXFlash - Sending emi data ...
DAXFlash - DRAM setup passed.
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Upload data was accepted. Jumping to stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       KM8V8001JM-B81
DAXFlash - UFS MID:      0xce
DAXFlash - UFS CID:      ce014b4d3856383030314a4d2d423831
DAXFlash - UFS FWVer:    31303030
DAXFlash - UFS Serial:   336261616466313432633064
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - HW-CODE         : 0x788
DAXFlash - HWSUB-CODE      : 0x8A00
DAXFlash - HW-VERSION      : 0xCA00
DAXFlash - SW-VERSION      : 0x0
DAXFlash - CHIP-EVOLUTION  : 0x0
DAXFlash - DA-VERSION      : 1.0
DAXFlash - Extensions were accepted. Jumping to extensions...
DAXFlash - DA Extensions successfully added
![5627cf02ead78044f20f3f430d1ca3e](https://github.com/o0Mardev/android_device_oppo_OP4B9B/assets/51497452/bf7dc874-ca41-4ad5-91fd-89bbd0c72106)

**Comment by o0Mardev** [comment]
I just read the issue now, sorry to hear that recovery doesn't work for you and I don't think recovery made any changes to the data partition.
Rather I think the problem is because the recovery does not work in the PCPM00 model, see here: [xda post](https://forum.xda-developers.com/t/recovery-unofficial-twrp-for-oppo-a91.4600477/post-88695281).
I think I now have confirmation that recovery does not work on this model, I will add it in the readme.

**Comment by o0Mardev** [comment]
If you have anything else to add feel free to comment further.
